Document: dhash
Title: Debian dhash Manual
Author: <insert document author here>
Abstract: This manual describes what dhash is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dhash/dhash.sgml.gz

Format: postscript
Files: /usr/share/doc/dhash/dhash.ps.gz

Format: text
Files: /usr/share/doc/dhash/dhash.text.gz

Format: HTML
Index: /usr/share/doc/dhash/html/index.html
Files: /usr/share/doc/dhash/html/*.html
